Traceback (most recent call last):
  File "evaluate_agents.py", line 163, in <module>
    raise Exception('There is no agent.py or env_info.txt!')
Exception: There is no agent.py or env_info.txt!
